device-name: "D-LinkCam"

dir-mud-profiles: "/home/padfoot/projects/iot-eval-framework/evaluation/mudgee/result"

dir-pcaps: "/home/padfoot/projects/iot-eval-framework/datasets/captures_IoT_Sentinel/D-LinkCam"