device-name: "D-LinkCam"
default-gateway-ip: "10.10.10.1"

dir-mud-profiles: "/home/chakshu/Documents/projects/iot_security/iot-eval-framework/evaluation/mudgee/result"

dir-pcaps: "/home/chakshu/Documents/projects/iot_security/iot-eval-framework/datasets/captures_IoT_Sentinel/D-LinkCam"